### ISSUE TITLE
OAuth flow does not handle cancel

### ISSUE THREAD

**Issue by trilleplay** [3ventic/moderation-station-auther#2]
If I choose to cancel authorization on Discords authorization page for the application it forwards me to the part where I link my Twitch, even if it should actually validate that it recieved a valid response from Discord before moving on. A workaround for this would to be handle the Twitch intergration from Discord aswell, since Discord has a scope: `&scope=connections` that lets you get a the users twitch username (if linked.)

**Comment by 3ventic** [comment]
Going to solve it by handling cancelled responses properly. Using Discord connections has two flaws for us: users may not want to connect their Twitch to their Discord, and they might have multiple connections (which would require implementing a selection UI instead of reusing the oauth flow).
